In [ ]:
import pandas as pd

:

In [3]:
#read data Titanic
df = pd.read_csv('Titanic.csv')

In [4]:
df.head()  # view first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.shape #check the number of rows and columns

(891, 12)

In [6]:
df.info()  #know information about the columns, data types, and null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
DROP_COLUMNS = ["PassengerId", "Name", "Ticket"]

df.drop(DROP_COLUMNS, axis=1, inplace=True, errors='ignore') #To drop specific columns from a DataFrame

In [10]:
from config import DROP_COLUMNS
def drop_cols(df:pd.DataFrame, cols: list[str]) ->pd.DataFrame:
    """
    Drop specifc columns from a DataFrame.
    """
    return df.drop(columns=cols)

In [11]:
class student:  #create a student class
    def __init__(self,name) ->None:  #Initialize the object with a name
        self.name = name  #store the student's name
    @property  #Create a getter for name
    def name(self):   #Get the student's name
        return self._name  #Return the name 
    @name.setter #Create a setter for name
    def name(self, value): # set a new name
        self._name = value #Updata the student's name

In [12]:
s1 = student("neama") #Create a student object with the name "neama"
s1.name # Get the student's name

'neama'

In [ ]:
dtypes = df.dtypes # Get the data type of each colum
n_uniq = df.nunique # count the number of unique values in each column
pd.DataFrame({"dtype:":dtypes, "Num_unique":n_uniq}).T #Create a DataFrame showing data types and number of unique values

In [7]:
def drop_cols(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    return df.drop(columns=cols, errors='ignore')

In [8]:
x = ["PassengerId", "Name", "Ticket"]
df.drop(x, axis=1, inplace=True, errors='ignore')

In [ ]:
drop_cols(def , Drop_COLS)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [10]:
dtype = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtypes":dtype, "N_uniques": n_uniq})

           Dtypes  N_uniques
Survived    int64          2
Pclass      int64          3
Sex        object          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin      object        147
Embarked   object          3

In [11]:
cols = ["Survived", "Pclass", "Sex", "SibSp", "Parch", "Embarked"]
df[cols] = df[cols].astype("category")
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,object,category

In [12]:
def get_data_summary(df):
    return pd.DataFrame({"Dtypes ": df.dtypes, "N_uniques ": df.nunique()}).T

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    category
 1   Pclass    891 non-null    category
 2   Sex       891 non-null    category
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    category
 5   Parch     891 non-null    category
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    category
dtypes: category(6), float64(2), object(1)
memory usage: 27.4+ KB

In [13]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [21]:
null = df.isnull().sum()
ratio = (null / df.shape[0]) * 100
pd.DataFrame({"null": null, "ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [24]:
df = df.dropna(subset=['Embarked'])
pd.DataFrame({"null": null, "ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [32]:
df = df.drop("Cabin", axis=1, errors='ignore')

In [34]:
#df.describe
median =df['Age'].median()
df['Age'] = df['Age'].fillna(median)

In [41]:
num_cols = df.select_dtypes("number").columns
for col in num_cols:
    Q1 =df[col].quantile(.25)
    Q3 =df[col].quantile(.75)
    #print(Q1,Q3)
    IQR =Q3-Q1
    lower_fence =Q1-1.2*IQR
    upper_fence =Q1-1.2*IQR


    lower_outliers = df[df[col] < lower_fence][col].values
    print(lower_fence)
    upper_outliers = df[df[col] > lower_fence][col].values
    #print(upper_fence)

6.4
-19.829239999999995

In [38]:
df.describe

<bound method NDFrame.describe of     Survived Pclass     Sex   Age SibSp Parch     Fare Embarked
0          0      3    male  22.0     1     0   7.2500        S
1          1      1  female  38.0     1     0  71.2833        C
2          1      3  female  26.0     0     0   7.9250        S
3          1      1  female  35.0     1     0  53.1000        S
4          0      3    male  35.0     0     0   8.0500        S
..       ...    ...     ...   ...   ...   ...      ...      ...
886        0      2    male  27.0     0     0  13.0000        S
887        1      1  female  19.0     0     0  30.0000        S
888        0      3  female  28.0     1     2  23.4500        S
889        1      1    male  26.0     0     0  30.0000        C
890        0      3    male  32.0     0     0   7.7500        Q

[889 rows x 8 columns]>