In [3]:
import numpy as np
np.random.random((3, 3))

array([[0.25176571, 0.95496382, 0.14937413],
       [0.39726197, 0.21378315, 0.05569441],
       [0.43313879, 0.80341191, 0.50389212]])

In [10]:
import numpy as np

arr = np.random.randint(0, 11, (5, 5))

In [ ]:
import numpy as np
mat1 = np.ones((3, 4))
mat2 = np.zeros((5, 3 ))
np.savez('file.npz',ones_mat = mat1, zeros_mat=mat2)

In [11]:
v = np.array([1,  3, 5, 0])
np.all(v>1)

np.False_

In [12]:
v = np.array([1,  3, 5, 0])
np.any(v>1)

np.True_

In [14]:
v1 =np.array([1, 2, 3,4,5])
v2=np.array([ 2, 3,0,5,6])
np.isclose(v1,v2,atol=1.)

array([ True,  True, False,  True,  True])

In [15]:
v =np.array([2,4,3,4,10])
condition =v >= 4
print(condition)

[False  True False  True  True]

In [ ]:
v =np.array([2,4,3,4,10])
condition =v >= 4
print(condition)

In [19]:
import pandas as pd
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [24]:
import pandas as pd
s = pd.Series([1,2,3,4],index = ["A","B","C","D"])
type(s)

pandas.core.series.Series

In [25]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}   
type(data)

list

In [27]:
colu=['lst','sal','dep']
df = pd.DataFrame(data)
df

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

In [31]:
df[:]

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

In [32]:
df.dtypes

0     int64
1     int64
2    object
dtype: object

In [ ]:
cols =['id','sal']
df[clos] = df[cols].astype('int')
df.dtypes

In [ ]:
df head(3)

In [36]:
df.tail

<bound method NDFrame.tail of    0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz>

In [39]:
df.describe(include='object')

          2
count     4
unique    4
top     abc
freq      1

In [40]:
df.describe(include=['category', 'object'])

          2
count     4
unique    4
top     abc
freq      1

In [42]:
de['col2']

NameError: name 'de' is not defined

In [43]:
df.col2.values_counts()

AttributeError: 'DataFrame' object has no attribute 'col2'

In [44]:
print(df.columns)

RangeIndex(start=0, stop=3, step=1)

In [45]:
df.info

<bound method DataFrame.info of    0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz>

In [46]:
df[1].value_counts()

1
444    2
555    1
666    1
Name: count, dtype: int64

In [ ]:
class Solution {
public:
    int searchInsert(vector<int>& nums, int target) {
        int left = 0;
        int right = nums.size() - 1;

        while (left <= right) {
            int mid = (left + right) / 2;

            if (nums[mid] == target) {
                return mid;
            }
            else if (nums[mid] < target) {
                left = mid + 1;
            }
            else {
                right = mid - 1;
            }
        }

        return left;
    }
};